### ISSUE TITLE
has done~  tks

### ISSUE THREAD

**Issue by 9a-aaaaaaaa** [LyyZzzz/calendar#1]
**Describe the bug**
A clear and concise description of what the bug

**Comment by LyyZzzz** [comment]
wx：li18756105323


------------------ 原始邮件 ------------------
发件人: "仇彦龙"<notifications@github.com>;
发送时间: 2019年9月3日(星期二) 中午1:04
收件人: "LyyZzzz/calendar"<calendar@noreply.github.com>;
抄送: "Subscribed"<subscribed@noreply.github.com>;
主题: [LyyZzzz/calendar] 可否加微信 (#1)




Describe the bug
 A clear and concise description of what the bug is.
 有几个地方没看明白，可否留下微信赐教一下

**Comment by LyyZzzz** [comment]
wx:&nbsp; li18756105323

---原始邮件---
发件人: "仇彦龙"<notifications@github.com&gt;
发送时间: 2019年9月3日(星期二) 中午1:04
收件人: "LyyZzzz/calendar"<calendar@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [LyyZzzz/calendar] 可否加微信 (#1)



Describe the bug
 A clear and concise description of what the bug is.
 有几个地方没看明白，可否留下微信赐教一下
